name: GH Project Board Sync

on:
  pull_request:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_AUTHOR_DEFAULT: DerekRoberts
  PROJECT_URL: https://github.com/orgs/bcgov/projects/16
  VERBOSE: true
  CONFIG_FILE: rules.yml
  OVERRIDE_REPOS: nr-nerds

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: '22'

      - name: Compute update window hours
        id: compute
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "hours=1" >> "$GITHUB_OUTPUT"
          else
            echo "hours=24" >> "$GITHUB_OUTPUT"
          fi

      - name: Install dependencies
        run: npm ci

      - name: Show Project Configuration
        run: |
          echo "Project Configuration:"
          echo "  PROJECT_URL: ${{ env.PROJECT_URL }}"
          echo "  VERBOSE: ${{ env.VERBOSE }}"
          echo "  GITHUB_AUTHOR: ${{ env.GITHUB_AUTHOR_DEFAULT }}"
          echo ""
          echo "Workflow Context:"
          echo "  Event: ${{ github.event_name }}"
          echo "  Ref: ${{ github.ref }}"
          echo "  Concurrency Group: ${{ github.workflow }}"
          echo "  Run ID: ${{ github.run_id }}"
          echo ""
          echo "Using hardcoded project URL for development"

      - name: Run Project Board Sync
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          GITHUB_AUTHOR: ${{ env.GITHUB_AUTHOR_DEFAULT }}
          PROJECT_URL: ${{ env.PROJECT_URL }}
          UPDATE_WINDOW_HOURS: ${{ steps.compute.outputs.hours }}
          VERBOSE: ${{ env.VERBOSE }}
          CONFIG_FILE: ${{ env.CONFIG_FILE }}
        run: npm run start
