name: GH Project Board Sync

on:
  pull_request:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:
    inputs:
      project_url:
        description: 'GitHub project URL (e.g., https://github.com/orgs/bcgov/projects/16)'
        required: false
        default: 'https://github.com/orgs/bcgov/projects/16'
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies (root)
        run: npm ci
        
      - name: Show Project Configuration
        run: |
          echo "Project Configuration:"
          echo "  PROJECT_URL: https://github.com/orgs/bcgov/projects/16"
          echo "  VERBOSE: true"
          echo "  GITHUB_AUTHOR: ${{ github.actor }}"
          echo ""
          echo "Using hardcoded project URL for development"
        
      - name: Build action
        run: npm run package
       
      - name: Run Project Sync Action
        uses: ./
        with:
          token: ${{ secrets.PROJECT_SYNC_TOKEN }}
          project_url: ${{ inputs.project_url || '' }}
          github_author: ${{ github.actor }}
          verbose: ${{ inputs.verbose || true }}
