name: GH Project Board Sync

on:
  pull_request:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync:
    concurrency:
      group: project-board-sync
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: packages/project-board-sync/project-board-sync
        run: npm ci

      - name: Show Project Configuration
        run: |
          echo "Project Configuration:"
          echo "  PROJECT_URL: https://github.com/orgs/bcgov/projects/16"
          echo "  VERBOSE: true"
          echo "  GITHUB_AUTHOR: ${{ github.actor }}"
          echo ""
          echo "Using hardcoded project URL for development"

      - name: Run Project Board Sync (PR)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          GITHUB_AUTHOR: ${{ github.actor }}
          PROJECT_URL: https://github.com/orgs/bcgov/projects/16
          UPDATE_WINDOW_HOURS: '1'
          VERBOSE: true
        working-directory: packages/project-board-sync/project-board-sync
        run: npm run start

      - name: Run Project Board Sync
        if: ${{ github.event_name != 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          GITHUB_AUTHOR: ${{ github.actor }}
          PROJECT_URL: https://github.com/orgs/bcgov/projects/16
          VERBOSE: true
        working-directory: packages/project-board-sync/project-board-sync
        run: npm run start
